name: Update sub-web

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
    - uses: actions/checkout@v2

    - name: Update sub-web
      run: |
        sudo rm -rf sub-web
        git clone https://github.com/Clown1i/sub-web.git

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Get dependencies and build
      run: |
        cd sub-web
        yarn install
        yarn build
        
    - name: Update and clean
      run: |
        cd $GITHUB_WORKSPACE
        mkdir temp
        sudo cp -rf sub-web/dist/* temp/
        sudo rm -rf sub-web
        sudo mv temp sub-web
        
    - name: Add & Commit
      uses: EndBug/add-and-commit@v6
      with:
        author_name: GitHub Action
        message: "Update sub-web"
      env:
        token: ${{ secrets.GITHUB_TOKEN }}
